### ISSUE TITLE
Проверка лабораторной работы 2

### ISSUE THREAD

**Issue by MiZhig** [MiZhig/TRPO#1]
Работу выполнил:
- Жигалов Михаил Александрович

To: @evgeny-p

**Comment by evgeny-p** [comment]
1. Приложение компилируется с предупреждениями.
2. Неконсистентное форматирование: пробелы вокруг бинарных операторов, пробелы перед открывающей круглой скобкой при вызове функции, пробелы после запятых.

Для исправления замечаний:
1. Создать новую ветку.
2. По одному коммиту на каждое замечание.
3. Мерж в мастер с опцией `--no-ff`.
